version: '2'
services:
  test:
    build: .
    volumes:
     - .:/usr/src/app
     - ./.m2-cache:/root/.m2
    depends_on:
     - redis
    environment:
     - TEST_REDIS_HOST=redis
     - TEST_REDIS_PORT=6379
     - TEST_REDIS_DB=0
     - GLOBAL_JWT_SECRETS=TEST,TEST2
     - TEST_S3_KEY=${S3_KEY}
     - TEST_S3_SECRET=${S3_SECRET}
     - TEST_S3_BUCKET_NAME=${S3_BUCKET_NAME}
     - TEST_S3_REGION_NAME=${S3_REGION_NAME}
     - GLOBAL_ARTIFACT_URL_BASE=https://artifact.eventdata.crossref.org
     - GLOBAL_EVENT_BUS_BASE=https://bus.eventdata.crossref.org
     - QUERY_PREFIX_WHITELIST_ARTIFACT_NAME=crossref-doi-prefix-list
     - QUERY_WHITELIST_ARTIFACT_NAME=crossref-sourcelist


    command: "lein test"

  redis:
    image: redis
