version: '2'
services:
  test:
    build: .
    volumes:
     - .:/usr/src/app
     - ./.m2-cache:/root/.m2
    depends_on:
     - redis
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - REDIS_DB=0
     - JWT_SECRETS=TEST,TEST2
     - S3_KEY=${S3_KEY}
     - S3_SECRET=${S3_SECRET}
     - S3_BUCKET_NAME=${S3_BUCKET_NAME}
     - S3_REGION_NAME=${S3_REGION_NAME}
     - STATUS_SERVICE=http://localhost:8003
     - ARTIFACT_BASE=http://d1v52iseus4yyg.cloudfront.net
    command: "lein test"

  redis:
    image: redis
