version: '2'
services:
  test:
    build: .
    volumes:
     - .:/usr/src/app
     - ./.m2-cache:/root/.m2
    depends_on:
     - redis
    environment:
     - TEST_REDIS_HOST=redis
     - TEST_REDIS_PORT=6379
     - TEST_REDIS_DB=0
     - GLOBAL_JWT_SECRETS=TEST,TEST2
     - GLOBAL_ARTIFACT_BASE=http://artifact-test
     - GLOBAL_EVENT_BUS_BASE=https://bus.eventdata.crossref.org
    command: "lein test"

  redis:
    image: redis
