version: '2'
services:
  test:
    build: .
    volumes:
     - .:/usr/src/app
     - ./.m2-cache:/root/.m2
    depends_on:
     - redis
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - REDIS_DB=0
     - STATUS_SERVICE=http://localhost:8003
     - JWT_SECRETS=TEST,TEST2
     - ARTIFACT_BASE=http://artifact-test
    command: "lein test"

  redis:
    image: redis
